<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.2 Hypothesis Testing for mean \(\mu\) | INTRO STATS WORKBOOK</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook.</p>" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="4.2 Hypothesis Testing for mean \(\mu\) | INTRO STATS WORKBOOK" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.2 Hypothesis Testing for mean \(\mu\) | INTRO STATS WORKBOOK" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook.</p>" />
  

<meta name="author" content="Dr Mostafa" />


<meta name="date" content="2025-03-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="quick-review-on-inference-for-mean.html"/>
<link rel="next" href="linear-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="checkArrange.js"></script>
<script src="checkOptions.js"></script>
<script src="checkShort.js"></script>
<script src="checkBucket.js"></script>
<script src="dragDrop.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">INTRO STATS WORKBOOK</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="introduction-to-data.html"><a href="introduction-to-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="data-types.html"><a href="data-types.html"><i class="fa fa-check"></i><b>1.1</b> Data Types</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="data-types.html"><a href="data-types.html#objectives"><i class="fa fa-check"></i><b>1.1.1</b> Objectives</a></li>
<li class="chapter" data-level="1.1.2" data-path="data-types.html"><a href="data-types.html#overview"><i class="fa fa-check"></i><b>1.1.2</b> Overview</a></li>
<li class="chapter" data-level="1.1.3" data-path="data-types.html"><a href="data-types.html#solved-problems"><i class="fa fa-check"></i><b>1.1.3</b> Solved Problems</a></li>
<li class="chapter" data-level="1.1.4" data-path="data-types.html"><a href="data-types.html#exercises"><i class="fa fa-check"></i><b>1.1.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="summarizing-numerical-data.html"><a href="summarizing-numerical-data.html"><i class="fa fa-check"></i><b>1.2</b> Summarizing Numerical Data</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="summarizing-numerical-data.html"><a href="summarizing-numerical-data.html#objectives-1"><i class="fa fa-check"></i><b>1.2.1</b> Objectives</a></li>
<li class="chapter" data-level="1.2.2" data-path="summarizing-numerical-data.html"><a href="summarizing-numerical-data.html#overview-1"><i class="fa fa-check"></i><b>1.2.2</b> Overview</a></li>
<li class="chapter" data-level="1.2.3" data-path="summarizing-numerical-data.html"><a href="summarizing-numerical-data.html#solved-problem"><i class="fa fa-check"></i><b>1.2.3</b> Solved Problem</a></li>
<li class="chapter" data-level="1.2.4" data-path="summarizing-numerical-data.html"><a href="summarizing-numerical-data.html#exercises-1"><i class="fa fa-check"></i><b>1.2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="summarizing-categorical-data.html"><a href="summarizing-categorical-data.html"><i class="fa fa-check"></i><b>1.3</b> Summarizing Categorical Data</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="summarizing-categorical-data.html"><a href="summarizing-categorical-data.html#objectives-2"><i class="fa fa-check"></i><b>1.3.1</b> Objectives</a></li>
<li class="chapter" data-level="1.3.2" data-path="summarizing-categorical-data.html"><a href="summarizing-categorical-data.html#overview-2"><i class="fa fa-check"></i><b>1.3.2</b> Overview</a></li>
<li class="chapter" data-level="1.3.3" data-path="summarizing-categorical-data.html"><a href="summarizing-categorical-data.html#solved-problem-1"><i class="fa fa-check"></i><b>1.3.3</b> Solved Problem</a></li>
<li class="chapter" data-level="1.3.4" data-path="summarizing-categorical-data.html"><a href="summarizing-categorical-data.html#exercise"><i class="fa fa-check"></i><b>1.3.4</b> Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="probability-and-probability-distribution.html"><a href="probability-and-probability-distribution.html"><i class="fa fa-check"></i><b>2</b> Probability and Probability Distribution</a>
<ul>
<li class="chapter" data-level="2.1" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>2.1</b> Probability</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="probability.html"><a href="probability.html#objectives-3"><i class="fa fa-check"></i><b>2.1.1</b> Objectives</a></li>
<li class="chapter" data-level="2.1.2" data-path="probability.html"><a href="probability.html#overview-3"><i class="fa fa-check"></i><b>2.1.2</b> Overview</a></li>
<li class="chapter" data-level="2.1.3" data-path="probability.html"><a href="probability.html#solved-problems-1"><i class="fa fa-check"></i><b>2.1.3</b> Solved Problems</a></li>
<li class="chapter" data-level="2.1.4" data-path="probability.html"><a href="probability.html#exercises-2"><i class="fa fa-check"></i><b>2.1.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html"><i class="fa fa-check"></i><b>2.2</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#objectives-4"><i class="fa fa-check"></i><b>2.2.1</b> Objectives</a></li>
<li class="chapter" data-level="2.2.2" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#overview-4"><i class="fa fa-check"></i><b>2.2.2</b> Overview</a></li>
<li class="chapter" data-level="2.2.3" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#solved-problems-2"><i class="fa fa-check"></i><b>2.2.3</b> Solved Problems</a></li>
<li class="chapter" data-level="2.2.4" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#exercises-3"><i class="fa fa-check"></i><b>2.2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="binomial-distribution.html"><a href="binomial-distribution.html"><i class="fa fa-check"></i><b>2.3</b> Binomial Distribution</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="binomial-distribution.html"><a href="binomial-distribution.html#objectives-5"><i class="fa fa-check"></i><b>2.3.1</b> Objectives</a></li>
<li class="chapter" data-level="2.3.2" data-path="binomial-distribution.html"><a href="binomial-distribution.html#overview-5"><i class="fa fa-check"></i><b>2.3.2</b> Overview</a></li>
<li class="chapter" data-level="2.3.3" data-path="binomial-distribution.html"><a href="binomial-distribution.html#solved-problem-2"><i class="fa fa-check"></i><b>2.3.3</b> Solved Problem</a></li>
<li class="chapter" data-level="2.3.4" data-path="binomial-distribution.html"><a href="binomial-distribution.html#exercises-4"><i class="fa fa-check"></i><b>2.3.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="normal-distribution.html"><a href="normal-distribution.html"><i class="fa fa-check"></i><b>2.4</b> Normal Distribution</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="normal-distribution.html"><a href="normal-distribution.html#objectives-6"><i class="fa fa-check"></i><b>2.4.1</b> Objectives</a></li>
<li class="chapter" data-level="2.4.2" data-path="normal-distribution.html"><a href="normal-distribution.html#overview-6"><i class="fa fa-check"></i><b>2.4.2</b> Overview</a></li>
<li class="chapter" data-level="2.4.3" data-path="normal-distribution.html"><a href="normal-distribution.html#solved-problem-3"><i class="fa fa-check"></i><b>2.4.3</b> Solved Problem</a></li>
<li class="chapter" data-level="2.4.4" data-path="normal-distribution.html"><a href="normal-distribution.html#exercises-5"><i class="fa fa-check"></i><b>2.4.4</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="inference-for-proportion.html"><a href="inference-for-proportion.html"><i class="fa fa-check"></i><b>3</b> Inference for Proportion</a>
<ul>
<li class="chapter" data-level="3.1" data-path="point-estimates-and-sampling-variability.html"><a href="point-estimates-and-sampling-variability.html"><i class="fa fa-check"></i><b>3.1</b> Point Estimates and Sampling Variability</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="point-estimates-and-sampling-variability.html"><a href="point-estimates-and-sampling-variability.html#objectives-7"><i class="fa fa-check"></i><b>3.1.1</b> Objectives</a></li>
<li class="chapter" data-level="3.1.2" data-path="point-estimates-and-sampling-variability.html"><a href="point-estimates-and-sampling-variability.html#overview-7"><i class="fa fa-check"></i><b>3.1.2</b> Overview</a></li>
<li class="chapter" data-level="3.1.3" data-path="point-estimates-and-sampling-variability.html"><a href="point-estimates-and-sampling-variability.html#solved-problem-4"><i class="fa fa-check"></i><b>3.1.3</b> Solved Problem</a></li>
<li class="chapter" data-level="3.1.4" data-path="point-estimates-and-sampling-variability.html"><a href="point-estimates-and-sampling-variability.html#exercises-6"><i class="fa fa-check"></i><b>3.1.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="confidence-interval.html"><a href="confidence-interval.html"><i class="fa fa-check"></i><b>3.2</b> Confidence Interval</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="confidence-interval.html"><a href="confidence-interval.html#objectives-8"><i class="fa fa-check"></i><b>3.2.1</b> Objectives</a></li>
<li class="chapter" data-level="3.2.2" data-path="confidence-interval.html"><a href="confidence-interval.html#overview-8"><i class="fa fa-check"></i><b>3.2.2</b> Overview</a></li>
<li class="chapter" data-level="3.2.3" data-path="confidence-interval.html"><a href="confidence-interval.html#solved-problem-5"><i class="fa fa-check"></i><b>3.2.3</b> Solved Problem</a></li>
<li class="chapter" data-level="3.2.4" data-path="confidence-interval.html"><a href="confidence-interval.html#exercises-7"><i class="fa fa-check"></i><b>3.2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="hypothesis-testing-for-p.html"><a href="hypothesis-testing-for-p.html"><i class="fa fa-check"></i><b>3.3</b> Hypothesis Testing for <span class="math inline">\(p\)</span></a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="hypothesis-testing-for-p.html"><a href="hypothesis-testing-for-p.html#objectives-9"><i class="fa fa-check"></i><b>3.3.1</b> Objectives</a></li>
<li class="chapter" data-level="3.3.2" data-path="hypothesis-testing-for-p.html"><a href="hypothesis-testing-for-p.html#overview-9"><i class="fa fa-check"></i><b>3.3.2</b> Overview</a></li>
<li class="chapter" data-level="3.3.3" data-path="hypothesis-testing-for-p.html"><a href="hypothesis-testing-for-p.html#solved-problem-6"><i class="fa fa-check"></i><b>3.3.3</b> Solved Problem</a></li>
<li class="chapter" data-level="3.3.4" data-path="hypothesis-testing-for-p.html"><a href="hypothesis-testing-for-p.html#exercises-8"><i class="fa fa-check"></i><b>3.3.4</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="inference-for-mean.html"><a href="inference-for-mean.html"><i class="fa fa-check"></i><b>4</b> Inference for Mean</a>
<ul>
<li class="chapter" data-level="4.1" data-path="quick-review-on-inference-for-mean.html"><a href="quick-review-on-inference-for-mean.html"><i class="fa fa-check"></i><b>4.1</b> Quick Review on Inference for Mean</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="quick-review-on-inference-for-mean.html"><a href="quick-review-on-inference-for-mean.html#objectives-10"><i class="fa fa-check"></i><b>4.1.1</b> Objectives</a></li>
<li class="chapter" data-level="4.1.2" data-path="quick-review-on-inference-for-mean.html"><a href="quick-review-on-inference-for-mean.html#overview-10"><i class="fa fa-check"></i><b>4.1.2</b> Overview</a></li>
<li class="chapter" data-level="4.1.3" data-path="quick-review-on-inference-for-mean.html"><a href="quick-review-on-inference-for-mean.html#solved-problem-7"><i class="fa fa-check"></i><b>4.1.3</b> Solved Problem</a></li>
<li class="chapter" data-level="4.1.4" data-path="quick-review-on-inference-for-mean.html"><a href="quick-review-on-inference-for-mean.html#exercises-9"><i class="fa fa-check"></i><b>4.1.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="hypothesis-testing-for-mean-mu.html"><a href="hypothesis-testing-for-mean-mu.html"><i class="fa fa-check"></i><b>4.2</b> Hypothesis Testing for mean <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="hypothesis-testing-for-mean-mu.html"><a href="hypothesis-testing-for-mean-mu.html#objectives-11"><i class="fa fa-check"></i><b>4.2.1</b> Objectives</a></li>
<li class="chapter" data-level="4.2.2" data-path="hypothesis-testing-for-mean-mu.html"><a href="hypothesis-testing-for-mean-mu.html#overview-11"><i class="fa fa-check"></i><b>4.2.2</b> Overview</a></li>
<li class="chapter" data-level="4.2.3" data-path="hypothesis-testing-for-mean-mu.html"><a href="hypothesis-testing-for-mean-mu.html#solved-problem-8"><i class="fa fa-check"></i><b>4.2.3</b> Solved Problem</a></li>
<li class="chapter" data-level="4.2.4" data-path="hypothesis-testing-for-mean-mu.html"><a href="hypothesis-testing-for-mean-mu.html#exercises-10"><i class="fa fa-check"></i><b>4.2.4</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>5</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html"><i class="fa fa-check"></i><b>5.1</b> Introduction to Linear Regression</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#objectives-12"><i class="fa fa-check"></i><b>5.1.1</b> Objectives</a></li>
<li class="chapter" data-level="5.1.2" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#overview-12"><i class="fa fa-check"></i><b>5.1.2</b> Overview</a></li>
<li class="chapter" data-level="5.1.3" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#solved-problem-9"><i class="fa fa-check"></i><b>5.1.3</b> Solved Problem</a></li>
<li class="chapter" data-level="5.1.4" data-path="introduction-to-linear-regression.html"><a href="introduction-to-linear-regression.html#exercises-11"><i class="fa fa-check"></i><b>5.1.4</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">INTRO STATS WORKBOOK</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hypothesis-testing-for-mean-mu" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Hypothesis Testing for mean <span class="math inline">\(\mu\)</span><a href="hypothesis-testing-for-mean-mu.html#hypothesis-testing-for-mean-mu" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="objectives-11" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Objectives<a href="hypothesis-testing-for-mean-mu.html#objectives-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>By the end of this unit, students will be able to:</p>
<div class="blue-background">
<ul>
<li>Formulate claims about a population mean in the form of a null hypothesis and alternative hypothesis.</li>
<li>Conduct t-tests for testing claims about a single population mean based on one sample and paired samples.</li>
</ul>
</div>
</div>
<div id="overview-11" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Overview<a href="hypothesis-testing-for-mean-mu.html#overview-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>One sample t-test (Same framework as the Hypothesis Testing for proportion)</strong></p>
<p><strong>Steps:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Set up the hypotheses</p></li>
<li><p>Compute the t test statistic</p>
<p>Using sample with size <span class="math inline">\(n\)</span>, sample mean <span class="math inline">\(\bar{x}\)</span>, sample standard deviation <span class="math inline">\(s\)</span>, null value <span class="math inline">\(\mu_0\)</span>,</p>
<p><span class="math inline">\(T = \frac{\bar{x} - \mu_0}{s/\sqrt{n}}\)</span></p></li>
<li><p>Compute the p-value</p>
<p>Let t-test statistic <span class="math inline">\(t_1 = \frac{\bar{x} - \mu_0}{s/\sqrt{n}}\)</span> (from step 2)</p>
<ul>
<li><p>For left-sided test, p-value is <span class="math inline">\(P(T &lt; t_1)\)</span> use <code>pt(t, df)</code></p></li>
<li><p>For right-sided test, p-value is <span class="math inline">\(P(T &gt; t_1)\)</span> use <code>pt(t, df, lower.tail = FALSE)</code></p></li>
<li><p>For two-sided test, p-value is <span class="math inline">\(P(|T| &gt; |t_1|)\)</span> use <span class="math inline">\(2*pt(-|t_1|, df)\)</span> or <span class="math inline">\(2*pt(|t_1|, df, lower.tail = FALSE)\)</span></p></li>
</ul></li>
<li><p>Compare the p-value with the significance level <span class="math inline">\(\alpha\)</span> and make decision</p>
<ul>
<li><p>If p-value <span class="math inline">\(\leq \alpha\)</span>, then we have enough evidence to reject <span class="math inline">\(H_0\)</span> and substantiate <span class="math inline">\(H_a\)</span>;</p></li>
<li><p>If p-value &gt; <span class="math inline">\(\alpha\)</span>, then we do not have enough evidence to reject <span class="math inline">\(H_0\)</span></p></li>
<li><p>The default value of significance level is <span class="math inline">\(\alpha = 0.05\)</span></p></li>
</ul></li>
</ol>
<p><strong>Hypothesis testing for a single mean</strong></p>
<p>Once you have determined a one-mean hypothesis test is the correct procedure, there are four steps to completing the test:</p>
<p><strong>Prepare.</strong> Identify the parameter of interest, list out hypotheses, identify the significance level, and identify <span class="math inline">\(\bar x,s\)</span> and <span class="math inline">\(n\)</span>.</p>
<p><strong>Check.</strong> Verify conditions to ensure <span class="math inline">\(\bar x\)</span> is nearly normal.</p>
<p><strong>Calculate.</strong> If the conditions hold, compute <span class="math inline">\(SE\)</span>, compute the T-score, and identify the p-value.</p>
<p><strong>Conclude.</strong> Evaluate the hypothesis test by comparing the p-value to <span class="math inline">\(\alpha\)</span>, and provide a conclusion in the context of the problem/.</p>
<p><strong>Paired Data</strong></p>
<p>In an earlier edition of this text book, we found that Amazon prices were, on average, lower than those of the UCLA Bookstore for UCLA courses in 2010. It’s been several years, and many stores have adapted to the online market, so we wondered, how is the UCLA Bookstore doing today?</p>
<p>We sampled 201 UCLA courses. Of those, 68 required books could be found on Amazon. A portion of the data set from these courses is shown in the table below, where the prices are in US dollars.</p>
<table>
<colgroup>
<col width="11%" />
<col width="28%" />
<col width="16%" />
<col width="12%" />
<col width="11%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>subject</th>
<th>course_number</th>
<th>bookstore</th>
<th>amazon</th>
<th>price_difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>American Indian Studies</td>
<td>M10</td>
<td>47.97</td>
<td>47.45</td>
<td>0.52</td>
</tr>
<tr class="even">
<td>2</td>
<td>Anthropology</td>
<td>2</td>
<td>14.26</td>
<td>13.55</td>
<td>0.71</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Arts and Architecture</td>
<td>10</td>
<td>13.50</td>
<td>12.53</td>
<td>0.97</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="odd">
<td>68</td>
<td>Jewish studies</td>
<td>M10</td>
<td>35.96</td>
<td>32.40</td>
<td>3.56</td>
</tr>
</tbody>
</table>
<p><strong>Paired observations:</strong></p>
<p>Each textbook has two corresponding prices in the data set: one for the UCLA Bookstore and one for Amazon. When two sets of observations have this special correspondence, they are said to be <strong>paired</strong>.</p>
<p><strong>Paired data</strong></p>
<p>Two sets of observations are <em>paired</em> if each observation in one set has a special correspondence or connection with exactly one observation in the other data set.</p>
<p>To analyze paired data, it is often useful to look at the difference in outcomes of each pair of observations. In the textbook data, we look at the differences in prices, which is represented as the <code>price_difference</code> variable in the data set. Here the differences are taken as</p>
<p><span class="math display">\[  \text{UCLA Bookstore price} - \text{Amazon price} \]</span></p>
<p>It is important that we always subtract using a consistent order; here Amazon prices are always subtracted from UCLA prices. The first difference shown in the table above is computed as <span class="math inline">\(47.97 - 47.45 = 0.52\)</span>. Similarly, the second difference is computed as <span class="math inline">\(14.26 - 13.55 = 0.71\)</span>, and the third is <span class="math inline">\(13.50 - 12.53 = 0.97\)</span>. A histogram of the differences is shown in the figure below. Using differences between paired observations is a common and useful way to analyze paired data.</p>
<div class="float">
<img src="images/Figure7.9.png" style="width:80.0%" alt="A histogram of difference in prices for each book sampled." />
<div class="figcaption">A histogram of difference in prices for each book sampled.</div>
</div>
<p><strong>Inference for paired data</strong></p>
<p>To analyze a paired data set, we simply analyze the differences.</p>
<p><span class="math display">\[n_{diff} = 68~~~~~\bar{x}_{diff} = 3.58~~~~~s_{diff} = 13.42 \]</span></p>
<p>Lets set up a hypothesis test to determine whether, on average, there is a difference between Amazon’s price for a book and the UCLA bookstore’s price. Also, check the conditions for whether we can move forward with the test using the <span class="math inline">\(t\)</span>-distribution.</p>
<p>We are considering two scenarios: there is no difference or there is some difference in average prices.</p>
<p><span class="math display">\[H_0: \mu_{diff} = 0. \text{ There is no difference in the average textbook price.}\]</span></p>
<p><span class="math display">\[H_A: \mu_{diff} \ne 0. \text{ There is a difference in average prices.}\]</span></p>
<p>Next, we will check the independence and normality conditions.</p>
<p>The observations are based on a simple random sample, so independence is reasonable. While there are some outliers, <span class="math inline">\(n = 68\)</span> and none of the outliers are particularly extreme, so the normality of <span class="math inline">\(\bar x\)</span> is satisfied. With these conditions satisfied, we can move forward with the <span class="math inline">\(t\)</span>-distribution.</p>
<p>To compute the test, we need to compute the standard error associated with <span class="math inline">\(\bar{x}_{diff}\)</span> using the standard deviation of the differences (<span class="math inline">\(s_{diff} = 13.42\)</span>) and the number of differences (<span class="math inline">\(n_{diff} = 68\)</span>):</p>
<p><span class="math display">\[SE_{\bar{x}_{diff}} = \frac{s_{diff}}{\sqrt{n_{diff}}} = \frac{13.42}{\sqrt{68}} = 1.63\]</span></p>
<p>The test statistics is the T-score of <span class="math inline">\(\bar{x}_{diff}\)</span> under the null condition that the actual mean difference is 0:</p>
<p><span class="math display">\[T = \frac{\bar{x}_{diff} - 0}{SE_{\bar{x}_{diff}}} = \frac{3.58 - 0}{1.63} = 2.20\]</span></p>
<p>To visualize the p-value, the sampling distribution of <span class="math inline">\(\bar{x}_{diff}\)</span> is drawn as though <span class="math inline">\(H_0\)</span> is true, and the p-value is represented by the two shaded tails:</p>
<p><img src="images/Figure7.10.png" style="width:80.0%" /></p>
<p>The degrees of freedom is <span class="math inline">\(df = 68 -1 = 67\)</span>. Using R, we find the one-tail area of 0.0156. Doubling this area gives the p-value: 0.0312.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="hypothesis-testing-for-mean-mu.html#cb50-1" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(<span class="fl">2.20</span>, <span class="at">df =</span> <span class="dv">67</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.03125996</code></pre>
<p>Because the p-value is less than 0.05, we reject the null hypothesis. Amazon prices are, on average, lower than the UCLA Bookstore prices for UCLA courses.</p>
</div>
<div id="solved-problem-8" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Solved Problem<a href="hypothesis-testing-for-mean-mu.html#solved-problem-8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div id="exercises-10" class="section level3 hasAnchor" number="4.2.4">
<h3><span class="header-section-number">4.2.4</span> Exercises<a href="hypothesis-testing-for-mean-mu.html#exercises-10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Exercise 1</strong></p>
<p>Without finding the values, arrange the numbers from small to large:</p>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(P(Z &lt; -1.25)\)</span><br />
</li>
<li><span class="math inline">\(P(T &lt; -1.25)\)</span> with <span class="math inline">\(df=10\)</span><br />
</li>
<li><span class="math inline">\(P(T &lt; -1.25)\)</span> with <span class="math inline">\(df=15\)</span><br />
</li>
<li><span class="math inline">\(P(Z &gt; 1.35)\)</span><br />
</li>
<li><span class="math inline">\(P(T &gt; 1.35)\)</span> with <span class="math inline">\(df=10\)</span><br />
</li>
<li><span class="math inline">\(P(T &gt; 1.25)\)</span> with <span class="math inline">\(df=15\)</span></li>
</ol>
<p><span class="math display">\[ \_\_\_\_\_\_ &lt; \_\_\_\_\_\_ &lt; \_\_\_\_\_\_ &lt; \_\_\_\_\_\_ &lt; \_\_\_\_\_\_ &lt; \_\_\_\_\_\_ \]</span></p>
<p><strong>Exercise 2</strong></p>
<p>Use R calculator to find the values of the probability of t-distribution. Sketch the t-curve and shaded region.</p>
<ul>
<li><span class="math inline">\(P(T &lt; -1.25)\)</span> with <span class="math inline">\(df=10\)</span></li>
<li><span class="math inline">\(P(T &lt; -1.25)\)</span> with <span class="math inline">\(df=15\)</span></li>
<li><span class="math inline">\(P(T &gt; 1.35)\)</span> with <span class="math inline">\(df=10\)</span></li>
<li><span class="math inline">\(P(T &gt; 1.25)\)</span> with <span class="math inline">\(df=15\)</span></li>
</ul>
<p><strong>Exercise 3</strong></p>
<p>Use R calculator to find the critical t-value <span class="math inline">\((t_{\alpha/2})\)</span>, rounded the result to 4 decimal places.</p>
<ul>
<li>CL = 90%, <span class="math inline">\(n = 7\)</span></li>
<li>CL = 98%, <span class="math inline">\(n = 20\)</span></li>
<li>CL = 99%, <span class="math inline">\(n = 28\)</span></li>
<li>CL = 95%, <span class="math inline">\(n = 9\)</span></li>
</ul>
<p><strong>Exercise 4</strong></p>
<p>Find confidence interval with the sample information:</p>
<p><em>(a)</em> <span class="math inline">\(n=5, \bar{x}=4.1, s=1.2\)</span>, 90% confidence level</p>
<p><em>(b)</em> <span class="math inline">\(n=15, \bar{x}=4.1, s=1.2\)</span>, 90% confidence level</p>
<p><em>(c)</em> <span class="math inline">\(n=5, \bar{x}=4.1, s=1.2\)</span>, 98% confidence level</p>
<p><em>(d)</em> <span class="math inline">\(n=15, \bar{x}=4.1, s=1.2\)</span>, 98% confidence level</p>
<p><strong>Exercise 5</strong></p>
<p>What affects the width of the confidence interval? (You may use your observations from Exercise 4 for reference)</p>
<p><strong>Exercise 6</strong></p>
<p>(Working backwards) A 95% confidence interval for a population mean <span class="math inline">\(\mu\)</span> is given as (18.98, 20.02). This confidence interval is based on a simple random sample of 36 observations. Calculate the following:</p>
<p><em>(a)</em> The sample mean</p>
<p><em>(b)</em> The margin of error</p>
<p><em>(c)</em> The critical t-value (use t-distribution)</p>
<p><em>(d)</em> The standard error (use the result of c)</p>
<p><em>(e)</em> The sample standard deviation (use the result of d)</p>
<p><strong>Exercise 7</strong></p>
<p>Find the P-value for the given sample sizes and test statistic:</p>
<p><em>(a)</em> <span class="math inline">\(n=26\)</span>, <span class="math inline">\(T=2.485\)</span>, for right-sided test</p>
<p><em>(b)</em> <span class="math inline">\(n=18\)</span>, <span class="math inline">\(T=-1.45\)</span>, for left-sided test</p>
<p><em>(c)</em> <span class="math inline">\(n=26\)</span>, <span class="math inline">\(T=2.485\)</span>, for two-sided test</p>
<p><em>(d)</em> <span class="math inline">\(n=18\)</span>, <span class="math inline">\(T=-1.45\)</span>, for two-sided test</p>
<p><strong>Exercise 8</strong></p>
<p>A random sample of 25 New Yorkers were asked how much sleep they get per night. The result shows:</p>
<p><span class="math inline">\(n=25, \bar{x}=7.73, s=0.77\)</span></p>
<p>The point estimate suggests that New Yorkers sleep less than 8 hours per night on average. Is the result statistically significant?</p>
<p>Follow the steps to conduct the hypothesis test.</p>
<p><em>(a)</em> Write the hypotheses in symbols: <span class="math inline">\(H_0\)</span>: ____________ <span class="math inline">\(H_a\)</span>: ____________</p>
<p><em>(b)</em> Calculate the test statistic</p>
<p><em>(c)</em> Compute the P-value and draw a picture</p>
<p><em>(d)</em> What is the conclusion of the hypothesis test, using the significance level <span class="math inline">\(\alpha=0.05\)</span></p>
<p><em>(e)</em> If you were to construct a 90% confidence interval that corresponds to this hypothesis test, would you expect 8 hours a night on average to be in the interval?</p>
<p><strong>Exercise 9</strong></p>
<p>Georgianna claims that in a small city, the average child takes less than 5 years of piano lessons. We have a random sample of 20 children from the city, with a mean of 4.6 years of piano lessons and a standard deviation of 2.2 years. Evaluate Georgianna’s claim using a hypothesis test.</p>
<p><em>(a)</em> Write the hypotheses in symbols: <span class="math inline">\(H_0\)</span>: ____________ <span class="math inline">\(H_a\)</span>: ____________</p>
<p><em>(b)</em> Calculate the test statistic</p>
<p><em>(c)</em> Compute the P-value and draw a picture</p>
<p><em>(d)</em> What is the conclusion of the hypothesis test, using the significance level <span class="math inline">\(\alpha=0.05\)</span></p>

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="quick-review-on-inference-for-mean.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="linear-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/004-QA.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["MATH 224 Workbook.pdf", "MATH 224 Workbook.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
